# Generated by Django 4.2.7 on 2026-03-02 18:52

import chinook_app.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('AlbumId', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=160)),
            ],
            options={
                'db_table': 'Album',
                'ordering': ['Title'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('TrackId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('MediaTypeId', models.IntegerField()),
                ('GenreId', models.IntegerField(blank=True, null=True)),
                ('Composer', models.CharField(blank=True, max_length=220, null=True)),
                ('Milliseconds', models.IntegerField()),
                ('Bytes', models.IntegerField(blank=True, null=True)),
                ('UnitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Track',
                'ordering': ['TrackId'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('ArtistId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'Artist',
                'ordering': ['Name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, help_text='Upload a profile picture. Max size: 2MB', null=True, upload_to=chinook_app.models.user_avatar_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif']), chinook_app.models.validate_image_size])),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.CharField(choices=[('birth_year', '1. What is your birth year?'), ('father_birth_year', "2. What is your father's birth year?"), ('mother_name', "3. What is your mother's name?"), ('father_name', "4. What is your father's name?"), ('favourite_colour', '5. What is your favourite colour?')], max_length=50)),
                ('answer_1', models.CharField(max_length=255)),
                ('question_2', models.CharField(choices=[('birth_year', '1. What is your birth year?'), ('father_birth_year', "2. What is your father's birth year?"), ('mother_name', "3. What is your mother's name?"), ('father_name', "4. What is your father's name?"), ('favourite_colour', '5. What is your favourite colour?')], max_length=50)),
                ('answer_2', models.CharField(max_length=255)),
                ('question_3', models.CharField(choices=[('birth_year', '1. What is your birth year?'), ('father_birth_year', "2. What is your father's birth year?"), ('mother_name', "3. What is your mother's name?"), ('father_name', "4. What is your father's name?"), ('favourite_colour', '5. What is your favourite colour?')], max_length=50)),
                ('answer_3', models.CharField(max_length=255)),
                ('question_4', models.CharField(choices=[('birth_year', '1. What is your birth year?'), ('father_birth_year', "2. What is your father's birth year?"), ('mother_name', "3. What is your mother's name?"), ('father_name', "4. What is your father's name?"), ('favourite_colour', '5. What is your favourite colour?')], max_length=50)),
                ('answer_4', models.CharField(max_length=255)),
                ('question_5', models.CharField(choices=[('birth_year', '1. What is your birth year?'), ('father_birth_year', "2. What is your father's birth year?"), ('mother_name', "3. What is your mother's name?"), ('father_name', "4. What is your father's name?"), ('favourite_colour', '5. What is your favourite colour?')], max_length=50)),
                ('answer_5', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')])),
                ('comment', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chinook_app.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'track')},
            },
        ),
    ]
