# Generated by Django 5.2.7 on 2025-10-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinook_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='security_answer',
            field=models.CharField(blank=True, help_text='Answer to your security question', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='security_question',
            field=models.CharField(blank=True, choices=[('pet', 'What was the name of your first pet?'), ('city', 'What city were you born in?'), ('school', 'What was the name of your elementary school?'), ('mother_maiden', "What is your mother's maiden name?"), ('car', 'What was the model of your first car?')], help_text='Select a security question for password recovery', max_length=20, null=True),
        ),
    ]
