# Generated by Django 4.2.x

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chinook_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='ArtistId',
            field=models.ForeignKey(db_column='ArtistId', on_delete=django.db.models.deletion.CASCADE, to='chinook_app.artist'),
        ),
        migrations.AddField(
            model_name='track',
            name='AlbumId',
            field=models.ForeignKey(blank=True, db_column='AlbumId', null=True, on_delete=django.db.models.deletion.CASCADE, to='chinook_app.album'),
        ),
    ]