# Generated by Django 5.2.7 on 2025-10-26 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinook_app', '0002_userprofile_security_answer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.CharField(choices=[('birth_year', '1. What is your birth year?'), ('father_birth_year', "2. What is your father's birth year?"), ('mother_name', "3. What is your mother's name?"), ('father_name', "4. What is your father's name?"), ('custom_question', '5. Your custom security question')], max_length=50)),
                ('answer_1', models.CharField(max_length=255)),
                ('question_2', models.CharField(choices=[('birth_year', '1. What is your birth year?'), ('father_birth_year', "2. What is your father's birth year?"), ('mother_name', "3. What is your mother's name?"), ('father_name', "4. What is your father's name?"), ('custom_question', '5. Your custom security question')], max_length=50)),
                ('answer_2', models.CharField(max_length=255)),
                ('question_3', models.CharField(choices=[('birth_year', '1. What is your birth year?'), ('father_birth_year', "2. What is your father's birth year?"), ('mother_name', "3. What is your mother's name?"), ('father_name', "4. What is your father's name?"), ('custom_question', '5. Your custom security question')], max_length=50)),
                ('answer_3', models.CharField(max_length=255)),
                ('question_4', models.CharField(choices=[('birth_year', '1. What is your birth year?'), ('father_birth_year', "2. What is your father's birth year?"), ('mother_name', "3. What is your mother's name?"), ('father_name', "4. What is your father's name?"), ('custom_question', '5. Your custom security question')], max_length=50)),
                ('answer_4', models.CharField(max_length=255)),
                ('question_5', models.CharField(choices=[('birth_year', '1. What is your birth year?'), ('father_birth_year', "2. What is your father's birth year?"), ('mother_name', "3. What is your mother's name?"), ('father_name', "4. What is your father's name?"), ('custom_question', '5. Your custom security question')], max_length=50)),
                ('answer_5', models.CharField(max_length=255)),
                ('custom_question_text', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
