# Generated by Django 5.2.7 on 2025-10-26 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chinook_app', '0003_securityquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='security_answer',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='security_question',
        ),
    ]
