# Generated by Django 5.2.7 on 2025-11-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinook_app', '0004_remove_userprofile_security_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityquestion',
            name='custom_question_text',
        ),
        migrations.AlterField(
            model_name='securityquestion',
            name='question_1',
            field=models.CharField(choices=[('birth_year', '1. What is your birth year?'), ('father_birth_year', "2. What is your father's birth year?"), ('mother_name', "3. What is your mother's name?"), ('father_name', "4. What is your father's name?"), ('favourite_colour', '5. What is your favourite colour?')], max_length=50),
        ),
        migrations.AlterField(
            model_name='securityquestion',
            name='question_2',
            field=models.CharField(choices=[('birth_year', '1. What is your birth year?'), ('father_birth_year', "2. What is your father's birth year?"), ('mother_name', "3. What is your mother's name?"), ('father_name', "4. What is your father's name?"), ('favourite_colour', '5. What is your favourite colour?')], max_length=50),
        ),
        migrations.AlterField(
            model_name='securityquestion',
            name='question_3',
            field=models.CharField(choices=[('birth_year', '1. What is your birth year?'), ('father_birth_year', "2. What is your father's birth year?"), ('mother_name', "3. What is your mother's name?"), ('father_name', "4. What is your father's name?"), ('favourite_colour', '5. What is your favourite colour?')], max_length=50),
        ),
        migrations.AlterField(
            model_name='securityquestion',
            name='question_4',
            field=models.CharField(choices=[('birth_year', '1. What is your birth year?'), ('father_birth_year', "2. What is your father's birth year?"), ('mother_name', "3. What is your mother's name?"), ('father_name', "4. What is your father's name?"), ('favourite_colour', '5. What is your favourite colour?')], max_length=50),
        ),
        migrations.AlterField(
            model_name='securityquestion',
            name='question_5',
            field=models.CharField(choices=[('birth_year', '1. What is your birth year?'), ('father_birth_year', "2. What is your father's birth year?"), ('mother_name', "3. What is your mother's name?"), ('father_name', "4. What is your father's name?"), ('favourite_colour', '5. What is your favourite colour?')], max_length=50),
        ),
    ]
